version: '3.5'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234567
   
    volumes:
     - data:/var/lib/postgreesql/data
     -  type: tmpfs
        target: /dev/shm
      
  #docker-compose down -v
  #git pull postgres
  #docker-compose up